flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_animate: ^4.5.0